const KEYWORDS = [
  'creators to follow',
  'AI creators to follow',
  'AI influencers to follow',
  'AI accounts to follow',
  'AI people to follow',
  'AI experts to follow',
  'AI leaders to follow',
  'AI voices to follow',
  'AI builders to follow',
  'AI founders to follow',
  'AI researchers to follow',
  'who to follow in AI',
  'who to follow for AI',
  'who to follow in artificial intelligence',
  'people to follow in AI',
  'accounts you should follow for AI',
  'AI people you should follow',
  'top AI creators',
  'top AI influencers',
  'top AI experts',
  'top AI accounts',
  'top AI builders',
  'top AI voices',
  'top AI thought leaders',
  'best AI creators',
  'best AI influencers',
  'best AI experts',
  'best AI accounts',
  'best AI thought leaders',
  'best AI educators',
  'leading AI creators',
  'leading AI experts',
  'leading voices in AI',
  'must follow AI creators',
  'must follow AI influencers',
  'must follow AI accounts',
  'must follow AI experts',
  'AI creators you must follow',
  'AI influencers you must follow',
  'AI accounts you should follow',
  'AI creators you should follow',
  'AI creator list',
  'AI influencer list',
  'AI accounts list',
  'AI experts list',
  'recommended AI creators',
  'recommended AI influencers',
  'recommended AI experts',
  'AI creators recommendation',
  'AI experts recommendation',
  'AI creators roundup',
  'AI influencers roundup',
  'AI community leaders',
  'AI thought leaders',
  'AI content creators',
  'AI educators',
  'AI builders',
  'AI practitioners',
  'AI educators to follow',
  'AI builders to follow',
  'AI founders to follow',
  'AI creators on Instagram',
  'AI influencers on Instagram',
  'AI accounts on Instagram',
  'AI creators on TikTok',
  'AI influencers on LinkedIn',
  'AI content creators',
  'AI social media creators',
  'AI voices shaping the future',
  'AI experts shaping the future',
  'AI people you need to know',
  'AI people you should know',
  'AI innovators to follow',
  'AI pioneers to follow',
  'AI leaders to watch',
  'AI creators to watch',
  'follow these AI creators',
  'follow these AI experts',
  'follow these AI accounts',
];

module.exports = KEYWORDS;
